name: Publish release
on:
  push:
    tags:
      - "jakarta.**"
  workflow_dispatch:

jobs:
  release:
    name: Feature
    permissions:
      packages: write
    uses: navikt/fp-gha-workflows/.github/workflows/release-feature.yml@main
    with:
      release-version: $GITHUB_REF
      release-branch: 'jakarta_ee9'
    secrets: inherit
